apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Vaishnavisousuddi/gitops-nginx.git'
    targetRevision: main
    path: nginx-site
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
